### ISSUE TITLE
User can get a random park with details

### ISSUE THREAD

**Issue by louis-zhangxa** [louis-zhangxa/ajax-project#1]
## ⚙️ Feature

User can get a random park with details

## 📐 Functionality

once user click the button they will get a random park

## 🖼️ 
<img width="270" alt="Screen Shot 2022-11-15 at 9 54 39 AM" src="https://user-images.githubusercontent.com/114542582/201993344-13b2716e-938b-4cb1-b225-02a7f8528d58.png">
<img width="270" alt="Screen Shot 2022-11-15 at 9 54 50 AM" src="https://user-images.githubusercontent.com/114542582/201993358-e5b0c366-01d5-4e7b-a9ae-deddc6d511ef.png">

<img width="499" alt="Screen Shot 2022-11-15 at 9 55 15 AM" src="https://user-images.githubusercontent.com/114542582/201993536-0d03684c-3111-4c1f-86e8-ce0304b59f9e.png">

<img width="499" alt="Screen Shot 2022-11-15 at 9 55 25 AM" src="https://user-images.githubusercontent.com/114542582/201993549-74090b3a-0057-4c3f-bcd1-16842fdf690b.png">

## ✅ Task List

- [x] add a header with the name of app on the left
- [x] add a background for the webpage
- [x] Add a div[data-view="home-page"] to the HTML.
- [x] Add a div[data-view="park-detail] to the HTML
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] set div[data-view="park-detail] to display:none
- [x] Listen for 'click' events on the journal entry form and:
    - [x] make  div[data-view="home-page"] display:none and show the div[data-view="park-detail] 
    - [x] get data from API. a random object in it
    - [x] render the data to div[data-view="home-page"]
    - [x] make sure the formatting is correct like shows on the wireframe
- [x]  Listen for 'click' events on the name of app on header and:
     - [x] make  div[data-view="park-detail"] display:none and show the div[data-view="home-page"]
- [x]  Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors
