### ISSUE TITLE
User can search for a national park

### ISSUE THREAD

**Issue by louis-zhangxa** [louis-zhangxa/ajax-project#2]
## ⚙️ Feature

>User can search for a national park

## 📐 Functionality

> add a search bar for user to search for a specific park

## 🖼️ Wireframes
<img width="271" alt="Screen Shot 2022-11-15 at 10 21 22 AM" src="https://user-images.githubusercontent.com/114542582/201996375-4a5289be-e345-421c-a375-632660899d0e.png">
<img width="465" alt="Screen Shot 2022-11-15 at 10 21 02 AM" src="https://user-images.githubusercontent.com/114542582/201996422-9f52e2e0-9e03-41e9-8d6e-dc22a7638c27.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add a search bar for mobile 
- [x] add a search bar on the right side of header for desktop property
- [x] Ensure that the page looks nice on both mobile-sized and desktop-sized screens.
- [x] get the data user inputted in search bar
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors
