### ISSUE TITLE
User can see a list of search results

### ISSUE THREAD

**Issue by louis-zhangxa** [louis-zhangxa/ajax-project#3]
## ⚙️ Feature

User can see a list of search results

## 📐 Functionality

once user searched, a list of their search result will showup

## 🖼️ Wireframes
<img width="271" alt="Screen Shot 2022-11-15 at 10 23 25 AM" src="https://user-images.githubusercontent.com/114542582/201996885-e636a503-8bef-44d2-96a0-03304164686e.png">
<img width="271" alt="Screen Shot 2022-11-15 at 10 23 39 AM" src="https://user-images.githubusercontent.com/114542582/201996894-557a3d6a-a6d2-4a0c-906e-f0395dfced2d.png">

<img width="556" alt="Screen Shot 2022-11-15 at 10 24 00 AM" src="https://user-images.githubusercontent.com/114542582/201997049-82575f64-c907-468d-a0f7-a9a4a2bd9ecf.png">

<img width="556" alt="Screen Shot 2022-11-15 at 10 24 09 AM" src="https://user-images.githubusercontent.com/114542582/201997066-7950dfd2-2ac2-4be8-94dd-9847b5b99c1f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a div[data-view="park-list"] to the HTML
- [x] making a list with an item for every result in the search results from API make sure it looks nice on both mobile-sized and desktop-sized screens.
- [x] delete card in HTML, create a same skeleton dom tree
- [x] render the card 
- [x] once user click the picture of the card, go to the park detail page of the park on the card
- [x]  Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors
