### ISSUE TITLE
User can add national park to list of favorites or get another random park

### ISSUE THREAD

**Issue by louis-zhangxa** [louis-zhangxa/ajax-project#4]
## ⚙️ Feature

User can add national park to list of favorites or get another random park

## 📐 Functionality

user can add the park to their favorites , or get another random park on the park info page

## 🖼️ Wire
<img width="484" alt="Screen Shot 2022-11-15 at 10 27 18 AM" src="https://user-images.githubusercontent.com/114542582/201997517-b7b49486-2bb3-4706-be20-c469c70dc920.png">
frames
<img width="269" alt="Screen Shot 2022-11-15 at 10 27 34 AM" src="https://user-images.githubusercontent.com/114542582/201997529-c910372f-acfc-40b4-a633-e87b2fa774ce.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add two button(add to favorite & get another park) to the park info page
- [x] make sure it looks nice on both mobile-sized and desktop-sized screens.
- [x] create a localstorage for the park user added to their favorite so it will keep in there next time user open the page
- [x] make the get another park button same function like get-random-park on the home page
- [x]  Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors
