### ISSUE TITLE
User can view list of favorite national parks

### ISSUE THREAD

**Issue by louis-zhangxa** [louis-zhangxa/ajax-project#5]
## ⚙️ Feature

User can view list of favorite national parks

## 📐 Functionality

user can see the park the added to favorites , and they can also delete them.

## 🖼️ Wireframes
<img width="157" alt="Screen Shot 2022-11-15 at 10 29 16 AM" src="https://user-images.githubusercontent.com/114542582/201997931-b7c9d7c9-b56e-4476-a962-cfade27bfff0.png">
<img width="157" alt="Screen Shot 2022-11-15 at 10 29 28 AM" src="https://user-images.githubusercontent.com/114542582/201997945-7770652a-bef3-4c9c-8445-389a3e363502.png">
<img width="484" alt="Screen Shot 2022-11-15 at 10 29 45 AM" src="https://user-images.githubusercontent.com/114542582/201997962-2add2d89-432a-44fe-a727-df6c5259b0ae.png">
<img width="484" alt="Screen Shot 2022-11-15 at 10 29 51 AM" src="https://user-images.githubusercontent.com/114542582/201997979-e1b2e22a-53be-401f-b378-62313c7ca003.png">

## ✅ Task List

- [x] add a [div data-view = "favorite-list"]
- [x] add a link to this div in the header 
- [x] making a list with an item for every result in the localstorage, also delete button. make sure it looks nice on both mobile-sized and desktop-sized screens.
- [x] delete card in HTML, create a same skeleton dom tree
- [x] render the card
- [x] make sure the delete button can delete both the dom card and locastorage.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors
